/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Page;

import tubes.main;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;

public class detailUndangan2 extends javax.swing.JFrame {

    /**
     * Creates new form detailUndangan
     */
    public detailUndangan2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new Page.bgDetailUndangan();
        harga = new javax.swing.JLabel();
        stock = new javax.swing.JLabel();
        label = new javax.swing.JLabel();
        persenDiskon = new javax.swing.JLabel();
        minPembelian = new javax.swing.JLabel();
        buatUndangan = new javax.swing.JButton();
        upTo = new javax.swing.JLabel();
        diskonHarga = new javax.swing.JLabel();
        balik = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        harga.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jPanel1.add(harga);
        harga.setBounds(461, 110, 100, 21);

        stock.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jPanel1.add(stock);
        stock.setBounds(480, 130, 120, 40);

        label.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jPanel1.add(label);
        label.setBounds(450, 180, 120, 21);

        persenDiskon.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        persenDiskon.setForeground(new java.awt.Color(255, 153, 0));
        jPanel1.add(persenDiskon);
        persenDiskon.setBounds(460, 190, 110, 30);

        minPembelian.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jPanel1.add(minPembelian);
        minPembelian.setBounds(430, 240, 190, 30);

        buatUndangan.setBackground(new java.awt.Color(51, 255, 0));
        buatUndangan.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        buatUndangan.setText("Buat Undangan");
        jPanel1.add(buatUndangan);
        buatUndangan.setBounds(440, 320, 130, 40);

        upTo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        upTo.setForeground(new java.awt.Color(255, 153, 0));
        jPanel1.add(upTo);
        upTo.setBounds(480, 200, 70, 40);

        diskonHarga.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        diskonHarga.setForeground(new java.awt.Color(255, 153, 0));
        jPanel1.add(diskonHarga);
        diskonHarga.setBounds(440, 222, 150, 30);

        balik.setBackground(new java.awt.Color(153, 255, 0));
        jPanel1.add(balik);
        balik.setBounds(40, 560, 90, 70);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 701, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 663, Short.MAX_VALUE)
        );

        pack();

        buatUndangan.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                main.dataDiri();
            }
        });

        balik.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                main.backBeli(2);
            }

        });
    }// </editor-fold>//GEN-END:initComponents



    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel balik;
    public javax.swing.JButton buatUndangan;
    public javax.swing.JLabel diskonHarga;
    public javax.swing.JLabel harga;
    public javax.swing.JPanel jPanel1;
    public javax.swing.JLabel label;
    public javax.swing.JLabel minPembelian;
    public javax.swing.JLabel persenDiskon;
    public javax.swing.JLabel stock;
    public javax.swing.JLabel upTo;
    // End of variables declaration//GEN-END:variables
}
