package Page;


import tubes.main;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;

public class login extends javax.swing.JFrame {

    /**
     * Creates new form login
     */
    public login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">

    private void initComponents() {

        jPanel2 = new background();
        jLabel4 = new JLabel();
        username = new JTextField();
        jLabel5 = new JLabel();
        login = new JButton();
        register = new JLabel();
        password = new JPasswordField();
        jLabel1 = new JLabel();
        notif = new JLabel();

        setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
        setLocation(new Point(500, 200));

        jPanel2.setBackground(new Color(255, 255, 255));
        jPanel2.setLayout(null);

        jLabel4.setFont(new Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setText("Username");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(200, 200, 60, 15);

        username.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });
        jPanel2.add(username);
        username.setBounds(196, 220, 270, 30);

        jLabel5.setFont(new Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setText("Password");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(200, 280, 54, 15);

        login.setBackground(new Color(102, 153, 255));
        login.setText("LOGIN");
        jPanel2.add(login);
        login.setBounds(300, 380, 80, 30);

        register.setBackground(new Color(0, 0, 0));
        register.setFont(new Font("Tahoma", 0, 12)); // NOI18N
        register.setForeground(new Color(255, 255, 255));
        register.setText("Apakah anda sudah memiliki akun? Register");
        jPanel2.add(register);
        register.setBounds(230, 450, 235, 15);

       //Logic
        login.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                main.tombolLogin();
            }
        });


        register.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                main.tombolRegister();
            }

        });

        jPanel2.add(password);
        password.setBounds(196, 300, 270, 30);

        jLabel1.setText("jLabel1");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(220, 230, 27, 11);
        jPanel2.add(notif);
        notif.setBounds(200, 340, 400, 30);

        GroupLayout layout = new GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel2, GroupLayout.PREFERRED_SIZE, 660, GroupLayout.PREFERRED_SIZE)
                                .addGap(2, 2, 2))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel2, GroupLayout.PREFERRED_SIZE, 530, GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void jPasswordField2ActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    // Variables declaration - do not modify
    private javax.swing.JButton login;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel register;
    public javax.swing.JLabel notif;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel2;
    public javax.swing.JPasswordField password;
    public javax.swing.JTextField username;
    // End of variables declaration
}
