/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Page;

import tubes.main;

import java.awt.event.*;

/**
 *
 * @author Arwin Marinta
 */
public class orderPage extends javax.swing.JFrame {

    /**
     * Creates new form orderPage
     */
    public orderPage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new Page.bgOrder();
        jumlahPesanan = new javax.swing.JTextField();
        jumlahDiskon = new javax.swing.JLabel();
        UpTo = new javax.swing.JLabel();
        hargaDiskon = new javax.swing.JLabel();
        cashOnDelivery = new javax.swing.JLabel();
        rirahpay = new javax.swing.JLabel();
        totalPembayaran = new javax.swing.JLabel();
        gopay = new javax.swing.JLabel();
        metodePembayaran = new javax.swing.JLabel();
        bayar = new javax.swing.JButton();
        batalkanPembayaran = new javax.swing.JButton();
        hemat = new javax.swing.JLabel();
        stock = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        jumlahPesanan.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jumlahPesanan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jumlahPesananActionPerformed(evt);
            }
        });
        jPanel1.add(jumlahPesanan);
        jumlahPesanan.setBounds(110, 180, 70, 25);

        jumlahDiskon.setBackground(new java.awt.Color(255, 255, 255));
        jumlahDiskon.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jumlahDiskon.setForeground(new java.awt.Color(255, 153, 0));
        jPanel1.add(jumlahDiskon);
        jumlahDiskon.setBounds(100, 260, 260, 30);

        UpTo.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        UpTo.setForeground(new java.awt.Color(255, 153, 0));
        jPanel1.add(UpTo);
        UpTo.setBounds(100, 280, 260, 40);

        hargaDiskon.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        hargaDiskon.setForeground(new java.awt.Color(255, 153, 0));
        jPanel1.add(hargaDiskon);
        hargaDiskon.setBounds(100, 310, 260, 30);
        jPanel1.add(cashOnDelivery);
        cashOnDelivery.setBounds(110, 440, 200, 21);
        jPanel1.add(rirahpay);
        rirahpay.setBounds(110, 510, 210, 21);

        totalPembayaran.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jPanel1.add(totalPembayaran);
        totalPembayaran.setBounds(520, 320, 160, 50);
        jPanel1.add(gopay);
        gopay.setBounds(110, 470, 200, 30);
        jPanel1.add(metodePembayaran);
        metodePembayaran.setBounds(260, 380, 160, 30);

        bayar.setBackground(new java.awt.Color(51, 255, 0));
        bayar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        bayar.setText("Bayar");
        jPanel1.add(bayar);
        bayar.setBounds(530, 430, 150, 40);

        batalkanPembayaran.setBackground(new java.awt.Color(255, 51, 51));
        batalkanPembayaran.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        batalkanPembayaran.setText("Batalkan Pembayaran");
        batalkanPembayaran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                batalkanPembayaranActionPerformed(evt);
            }
        });
        jPanel1.add(batalkanPembayaran);
        batalkanPembayaran.setBounds(530, 480, 150, 40);

        hemat.setBackground(new java.awt.Color(255, 255, 255));
        hemat.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel1.add(hemat);
        hemat.setBounds(560, 350, 170, 60);

        stock.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel1.add(stock);
        stock.setBounds(290, 170, 170, 40);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 824, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 582, Short.MAX_VALUE)
        );

        pack();

        jumlahPesanan.addKeyListener(new KeyAdapter() {
            public void keyPressed(KeyEvent ke) {
                try {
                    if (!(jumlahPesanan.getText().equals("") || jumlahPesanan.getText() == null)) {
                        main.setHarga(Integer.parseInt(jumlahPesanan.getText()));
                    }
                } catch (Exception e) {
                    jumlahPesanan.setText("");
                }
            }
        });

        batalkanPembayaran.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                main.batalBayar();
            }
        });

        bayar.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                main.confirmBayar();
            }
        });

        cashOnDelivery.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                main.methodBayar(1);
            }

        });

        gopay.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                main.methodBayar(2);
            }

        });

        rirahpay.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                main.methodBayar(3);
            }

        });

    }// </editor-fold>//GEN-END:initComponents

    private void jumlahPesananActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jumlahPesananActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jumlahPesananActionPerformed

    private void batalkanPembayaranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_batalkanPembayaranActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_batalkanPembayaranActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel UpTo;
    public javax.swing.JButton batalkanPembayaran;
    public javax.swing.JButton bayar;
    public javax.swing.JLabel cashOnDelivery;
    public javax.swing.JLabel gopay;
    public javax.swing.JLabel hargaDiskon;
    public javax.swing.JLabel hemat;
    public javax.swing.JPanel jPanel1;
    public javax.swing.JLabel jumlahDiskon;
    public javax.swing.JTextField jumlahPesanan;
    public javax.swing.JLabel metodePembayaran;
    public javax.swing.JLabel rirahpay;
    public javax.swing.JLabel stock;
    public javax.swing.JLabel totalPembayaran;
    // End of variables declaration//GEN-END:variables
}
