/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Page;

import tubes.main;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;

/**
 *
 * @author Arwin Marinta
 */
public class tampilanUndangan extends javax.swing.JFrame {

    /**
     * Creates new form detailUndangan
     */
    public tampilanUndangan() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new Page.tampilUndangan();
        beli2 = new javax.swing.JButton();
        beli3 = new javax.swing.JButton();
        beli1 = new javax.swing.JButton();
        account = new javax.swing.JLabel();
        historyPenjualan = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(450, 200));

        jPanel1.setPreferredSize(new java.awt.Dimension(402, 51));
        jPanel1.setLayout(null);

        beli2.setBackground(new java.awt.Color(0, 255, 0));
        beli2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        beli2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconn/Keranjang 2.png"))); // NOI18N
        beli2.setText("Black White");
        beli2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                beli2ActionPerformed(evt);
            }
        });
        jPanel1.add(beli2);
        beli2.setBounds(290, 500, 190, 50);

        beli3.setBackground(new java.awt.Color(0, 255, 51));
        beli3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        beli3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconn/Keranjang 2.png"))); // NOI18N
        beli3.setText("Rose Love");
        jPanel1.add(beli3);
        beli3.setBounds(550, 500, 190, 50);

        beli1.setBackground(new java.awt.Color(0, 255, 51));
        beli1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        beli1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconn/Keranjang 2.png"))); // NOI18N
        beli1.setText("Golden");
        beli1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                beli1ActionPerformed(evt);
            }
        });
        jPanel1.add(beli1);
        beli1.setBounds(40, 500, 190, 50);

        account.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jPanel1.add(account);
        account.setBounds(680, 30, 60, 80);

        historyPenjualan.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jPanel1.add(historyPenjualan);
        historyPenjualan.setBounds(570, 30, 60, 80);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 779, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 613, Short.MAX_VALUE)
        );

        beli1.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                main.beli1();
            }
        });

        beli2.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                main.beli2();
            }
        });

        beli3.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                main.beli3();
            }
        });


        account.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                main.account();
            }

        });

        historyPenjualan.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                main.history();
            }

        });

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void beli2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_beli2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_beli2ActionPerformed

    private void beli1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_beli1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_beli1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel account;
    public javax.swing.JButton beli1;
    public javax.swing.JButton beli2;
    public javax.swing.JButton beli3;
    public javax.swing.JLabel historyPenjualan;
    public javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
